import {IWidget} from '../../modules/widget/models/widget';

export const WIDGET_DATA: IWidget[] = [
  {
    id: 1,
    name: 'Aurora',
    projectName: 'CRM-система для отдела продаж',
    type: 'progress',
    chartData: {
      tasksCompleted: 25,
      tasksTotal: 50,
      startDate: '2024-01-01',
      endDate: '2024-12-31',
    },
    order: 0,
  },
  {
    id: 2,
    name: 'Skyline',
    projectName: 'Облачная инфраструктура Skyline Cloud',
    type: 'statistics',
    chartData: {
      tasksCompleted: 75,
      tasksTotal: 140,
      startDate: '2023-06-01',
      endDate: '2024-03-31',
    },
    order: 1,
  },
  {
    id: 3,
    name: 'Quantum',
    projectName: 'Платформа аналитики Quantum Data',
    type: 'timeline',
    chartData: {
      tasksCompleted: 80,
      tasksTotal: 85,
      startDate: '2024-06-01',
      endDate: '2024-09-30',
    },
    order: 2,
  },
  {
    id: 4,
    name: 'Nexus',
    projectName: 'Система документооборота Nexus Workflow',
    type: 'progress',
    chartData: {
      tasksCompleted: 40,
      tasksTotal: 100,
      startDate: '2024-03-15',
      endDate: '2024-11-10',
    },
    order: 3,
  },
  {
    id: 5,
    name: 'Horizon',
    projectName: 'Корпоративный портал Horizon Intranet',
    type: 'timeline',
    chartData: {
      tasksCompleted: 15,
      tasksTotal: 60,
      startDate: '2024-04-01',
      endDate: '2024-10-15',
    },
    order: 4,
  },
  {
    id: 6,
    name: 'Orion',
    projectName: 'Мобильное приложение Orion Delivery',
    type: 'statistics',
    chartData: {
      tasksCompleted: 90,
      tasksTotal: 120,
      startDate: '2023-11-01',
      endDate: '2024-07-20',
    },
    order: 5,
  },
  {
    id: 7,
    name: 'Vertex',
    projectName: 'BI-система Vertex Analytics',
    type: 'progress',
    chartData: {
      tasksCompleted: 50,
      tasksTotal: 80,
      startDate: '2024-02-01',
      endDate: '2024-08-31',
    },
    order: 6,
  },
  {
    id: 8,
    name: 'Pulse',
    projectName: 'Система мониторинга здоровья Pulse',
    type: 'timeline',
    chartData: {
      tasksCompleted: 30,
      tasksTotal: 70,
      startDate: '2024-05-10',
      endDate: '2024-12-15',
    },
    order: 7,
  },
  {
    id: 9,
    name: 'Atlas',
    projectName: 'Геоплатформа Atlas GeoData',
    type: 'statistics',
    chartData: {
      tasksCompleted: 60,
      tasksTotal: 100,
      startDate: '2023-12-01',
      endDate: '2024-09-01',
    },
    order: 8,
  },
  {
    id: 10,
    name: 'Echo',
    projectName: 'Голосовой ассистент Echo Voice AI',
    type: 'progress',
    chartData: {
      tasksCompleted: 10,
      tasksTotal: 50,
      startDate: '2024-07-01',
      endDate: '2025-03-01',
    },
    order: 9,
  },
];
